  name: vita_valore
  description: "A new Flutter project."
  publish_to: 'none' 
  version: 1.0.0+1
  environment:
    sdk: '>=3.3.0 <4.0.0'
  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.6
  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.0
  flutter:
    uses-material-design: true
    
    assets:
      - assets/activities.json
      - assets/VitaValoreLogo.jpeg
      - assets/Ze_gotinha_da_agua.png

    fonts:
    - family: GlacialInd
      fonts:
        - asset: assets/fonts/glacial-indifference-2/GlacialIndifference-Bold.otf
          weight: 700
        - asset: assets/fonts/glacial-indifference-2/GlacialIndifference-Regular.otf
          weight: 400